# def d(x):
#     x/0
#     print("h")
# try:
#     d(4)
# except:
#     print("u have error")
# else:
#     print("function complited")
#     #finally 
# print("program is running ")

#####################################


def additoin(x, y):
          x = 10
          y = 20
          print("Addition:", x + b)

try:
 additoin(10, 20)
except Exception as e:
    print("You Have Error: ",e)
else:
    print("the operation is successful")
